@startuml "week_menu_usecase"
title Week Menu - UseCase Diagram \n
skinparam actorStyle awesome

actor User
actor App
usecase "Cadastrar\ncardápio" as createMenu
usecase "Ver lista\nde cardápios" as listMenu
usecase "Ver detalhes\ndo cardápio" as showMenu
usecase "Alterar\ncardápio" as updateMenu
usecase "Excluir\ncardápio" as deleteMenu
usecase "Adicionar\ncardápio do dia" as addMenuWeek
usecase "Listar dias\nda semana" as listWeekMenu
usecase "Ver cardápio\nda semana" as showWeekMenu

User -- createMenu
User -- listMenu
User -- showMenu
User -- updateMenu
User -- deleteMenu
User -- addMenuWeek
App -- listWeekMenu
User -- showWeekMenu

@enduml